[consumer]
open = true
proxy_addr = "http://127.0.0.1:8000"
proxy_http2 = false

[producer]
open = true

[[producer_clients]]
servers = [":9092"]
#多实例name区分
#name = ""

[[consumer_clients]]
servers = [":9092"]
group_id = "freedom"

# retry 避免离线后丢失 Topic, 所以使用 OffsetOldest。如果新增加group，手动设置该group 为最新offset
# kafka-consumer-groups --bootstrap-server 127.0.0.1:9092 --group retry_freedom --reset-offsets --all-topics --to-latest --execute
retry_count = 3
retry_group_id = "retry_freedom"
retry_prefix = "retry-"
retry_interval_sec = 45
retry_fail_prefix="fail-"