[consumer]
open = true
proxy_addr = "http://127.0.0.1:8000"
proxy_http2 = false

[producer]
open = true

[[producer_clients]]
servers = [":9092"]
#多实例name区分
#name = ""

[[consumer_clients]]
servers = [":9092"]
group_id = "freedom"
retry_count = 3
retry_group_id = "retry_freedom"
retry_prefix = "retry-"
retry_interval_sec = 60
retry_fail_prefix="fail-"